// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL = "https://fktdctzrtesjyvpjnsdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrdGRjdHpydGVzanl2cGpuc2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTgxNzMsImV4cCI6MjA2MzI5NDE3M30.J4iKDYHbSahK-BGIcDa4-jjM_4liSnkWff-EVuqsWsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);